### ISSUE TITLE
CMake Error:install TARGETS given no LIBRARY DESTINATION for shared library target

### ISSUE THREAD

**Issue by josh-zhu** [zhanghang1989/PyTorch-Encoding-Layer#2]
I try to install this package,but get the following error:

-- TORCH_BUILD_DIR: /usr/local/lib/python2.7/dist-packages/torch/lib
-- Autodetected CUDA architecture(s): 3.0
-- Torch_INSTALL_INCLUDE:/usr/local/lib/python2.7/dist-packages/torch/lib/include/usr/local/lib/python2.7/dist-packages/torch/lib/include/TH/usr/local/lib/python2.7/dist-packages/torch/lib/include/THC/home/ubuntu/pytorch/torch/lib/THC
CMake Error at CMakeLists.txt:78 (INSTALL):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "ENCODING".

-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/soushi/reg/DeepTEN/encoding/build/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu/soushi/reg/DeepTEN/encoding/build/CMakeFiles/CMakeError.log".
make: *** No rule to make target 'install'.  Stop.
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'extra_compile_args'
  warnings.warn(msg)

**Comment by zhanghang1989** [comment]
Hi, have you install PyTorch from source at your `$HOME` directory?

**Comment by josh-zhu** [comment]
O, I installed it on other place

**Comment by zhanghang1989** [comment]
You can manually change the path here: https://github.com/zhanghang1989/PyTorch-Encoding-Layer/blob/master/build.py#L41

**Comment by josh-zhu** [comment]
thx, it works now
