### ISSUE TITLE
Broken dependencies

### ISSUE THREAD

**Issue by ashr59** [zhanghang1989/PyTorch-Encoding-Layer#3]
@zhanghang1989 
Hi, 
when I tried to install the pack, I got this error:
`/home/PyTorch-Encoding-Layer-master/encoding/src/encoding_lib.cpp:12:26: fatal error: thc_encoding.h: No such file or directory
`
It seems that there are some broken dependencies in the package, right?
I thought it might be something related to my PyTorch installation, so I installed all the things from the scratch, but the error remained the same.

**Comment by zhanghang1989** [comment]
Hi @ashr59 ,
Have you installed PyTorch from source at your `$HOME` directory?
https://github.com/zhanghang1989/PyTorch-Encoding-Layer#installation

**Comment by ashr59** [comment]
@zhanghang1989 Yes, I did.

**Comment by zhanghang1989** [comment]
That is because the kernel compiling failed https://github.com/zhanghang1989/PyTorch-Encoding-Layer/blob/master/build.py#L31~L33

Can you check the path of the libraries https://github.com/zhanghang1989/PyTorch-Encoding-Layer/blob/master/build.py#L27~L28

**Comment by ashr59** [comment]
@zhanghang1989 Hi again, sorry I was a little busy with IFA. I'll check it, many thanks.

**Comment by zhanghang1989** [comment]
Hi @ashr59, let me know if you still have the problem. I am closing it temporarily, but feel free to reopen.
